name: Container Build & Push - CalculatorAPI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  IMAGENAME: calculatorapi
   
jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
            
    - name: format IMAGETAG
      run: |
        echo "IMAGETAG=v$(date "+%Y%m%d")-${{github.run_number }}" >> $GITHUB_ENV
    - name: format repo-owner lowercase
      run: |
        echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
      env:
        OWNER: '${{ github.repository_owner }}'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags:  >
          ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}, 
          ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGENAME }}:latest
